services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql3
    environment:
      MYSQL_ROOT_PASSWORD: asd123
    ports:
      - "3308:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
